<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1576064515036' stop='1576064680253'>
    <name>ENDEVOUR CYPRESS SITE TEST AUTOMATION</name>
    <title>ENDEVOUR CYPRESS SITE TEST AUTOMATION</title>
    <test-cases>
        <test-case start='1576064515037' status='failed' stop='1576064592778'>
            <name>verify that page content of a Cypress web site : FirstDataSets</name>
            <title>verify that page content of a Cypress web site : FirstDataSets</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at ontimeout (timers.js:436:11)
                    at tryOnTimeout (timers.js:300:5)
                    at listOnTimeout (timers.js:263:5)
                    at Timer.processTimers (timers.js:223:10)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1576064592779' status='failed' stop='1576064632058'>
            <name>verify that page content of a Cypress web site : SecondDataSets</name>
            <title>verify that page content of a Cypress web site : SecondDataSets</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at ontimeout (timers.js:436:11)
                    at tryOnTimeout (timers.js:300:5)
                    at listOnTimeout (timers.js:263:5)
                    at Timer.processTimers (timers.js:223:10)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1576064632059' status='failed' stop='1576064680248'>
            <name>verify that page content of a Cypress web site : ThirdDataSets</name>
            <title>verify that page content of a Cypress web site : ThirdDataSets</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at ontimeout (timers.js:436:11)
                    at tryOnTimeout (timers.js:300:5)
                    at listOnTimeout (timers.js:263:5)
                    at Timer.processTimers (timers.js:223:10)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>